WebApp/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using InternetForum.Core.Domain;
using InternetForum.WebApp.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using WebApp.Models;
using JwtRegisteredClaimNames = Microsoft.IdentityModel.JsonWebTokens.JwtRegisteredClaimNames;

namespace WebApp.Controllers
{
    public class PostController : Controller
    {
        public IConfiguration Configuration;
        private readonly UserManager<User> _userManager;

        public PostController(IConfiguration configuration, UserManager<User> userManager)
        {
            Configuration = configuration;
            _userManager = userManager;
        }

       
        public async Task<IActionResult> Index()
        {
            var tokenString = Utils.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();
            List<PostMV> posts = new List<PostMV>();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    posts = JsonConvert.DeserializeObject<List<PostMV>>(apiResponse);
                }
            }

            return View(posts);
        }
        
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var tokenString = Utils.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();
          
         
            PostMV r = new PostMV();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.DeleteAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        r = JsonConvert.DeserializeObject<PostMV>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction(nameof(Index));
            
        }
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            CreatePostMV post = new CreatePostMV();
            return await Task.Run(() => View(post));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreatePostMV post)
        {
            string _restpath = GetHostUrl().Content + CN();
            var tokenString = Utils.GenerateJSONWebToken();
            post.Author = _userManager.GetUserAsync(HttpContext.User).Result.Id;
           

            PostMV result = new PostMV();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(post);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");


                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<PostMV>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            string _restpath = GetHostUrl().Content + CN();


            PostMV post = new PostMV();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    post = JsonConvert.DeserializeObject<PostMV>(apiResponse);
                }
            }
            return View(post);
        }

        [HttpPost]
        //[Authorize]
        public async Task<IActionResult> Edit(EditPostMV post)
        {
            string _restpath = GetHostUrl().Content + CN();
            var tokenString = Utils.GenerateJSONWebToken();

            PostMV r = new PostMV();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(post);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.PutAsync($"{_restpath}/{post.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        r = JsonConvert.DeserializeObject<PostMV>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction(nameof(Index));
        }

       
       
        

        private ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            string cn = ControllerContext.RouteData.Values["controller"].ToString();
            return cn;
        }

    }
}

WebApp/Controllers/ReplyController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using InternetForum.Core.Domain;
using InternetForum.WebApp.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ReplyController : Controller
    {
        public IConfiguration _configuration;
        private readonly UserManager<User> _userManager;

        public ReplyController(IConfiguration configuration, UserManager<User> userManager)
        {
            _configuration = configuration;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int id)
        {
            var tokenString = Utils.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();
            var x = GetHostUrl().Content;
            PostMV tmp;

            List<ReplyMV> replies = new List<ReplyMV>();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                using (var response = await httpClient.GetAsync($"{_restpath}/post/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    replies = JsonConvert.DeserializeObject<List<ReplyMV>>(apiResponse);
                }

                if (x != null)
                {
                    using (var response = await httpClient.GetAsync($"{x}post/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        tmp = JsonConvert.DeserializeObject<PostMV>(apiResponse);



                        if (tmp != null)
                        {


                            ViewBag.PostId = id;
                            ViewBag.User = tmp.AuthorNickname;
                            ViewBag.Description = tmp.Description;
                            ViewBag.Date = tmp.Posted;
                            ViewBag.Title = tmp.Title;
                        }

                    }
                }

            }

           


            return View(replies);
        }
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id,int post)
        {
            string _restpath = GetHostUrl().Content + CN();
            var tokenString = Utils.GenerateJSONWebToken();
            ReplyMV r = new ReplyMV();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.DeleteAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        r = JsonConvert.DeserializeObject<ReplyMV>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction(nameof(Index), new { id=post });
        }
        
        
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create(int id)
        {
            CreateReplyMV s = new CreateReplyMV();
            s.Post = id;
            ViewBag.PostId = id;
            return await Task.Run(() => View(s));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateReplyMV s)
        {
            string _restpath = GetHostUrl().Content + CN();
            var tokenString = Utils.GenerateJSONWebToken();
            s.Author = _userManager.GetUserAsync(HttpContext.User).Result.Id;
            ReplyMV r = new ReplyMV();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        r = JsonConvert.DeserializeObject<ReplyMV>(apiResponse);
                    }

                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction(nameof(Index),new { id = s.Post });
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
           
            Console.Write("\n\n"+id+"\n\n");
            string _restpath = GetHostUrl().Content + CN();

            ReplyMV s = new ReplyMV();
            //s.PostId = post;
           

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    s = JsonConvert.DeserializeObject<ReplyMV>(apiResponse);
                    ViewBag.PostId = s.PostId;
                }
            }
           
            return View(s);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(EditReplyMV p)
        {

            string _restpath = GetHostUrl().Content + CN();
            var tokenString = Utils.GenerateJSONWebToken();
            var id = 0;


            ReplyMV result = new ReplyMV();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(p);
                    Console.Write(jsonString);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.PutAsync($"{_restpath}/{p.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<ReplyMV>(apiResponse);
                    }
                    
                    using (var response = await httpClient.GetAsync($"{_restpath}/{p.Id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
               
                        result = JsonConvert.DeserializeObject<ReplyMV>(apiResponse);
                        id = result.PostId;
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction("Index", new { id = id });
        }


    

       

        private ContentResult GetHostUrl()
        {
            var result = _configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            string cn = ControllerContext.RouteData.Values["controller"].ToString();
            return cn;
        }
    }
}

WebApp/Views/Post/Create.cshtml
@model WebApp.Models.CreatePostMV

<h4>Create Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Posts</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Post/Edit.cshtml
@model WebApp.Models.PostMV

<h4>Edit Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Post/Index.cshtml
@model IEnumerable<WebApp.Models.PostMV>

<div>

    @if (!User.Identity.IsAuthenticated)
    {
        <div class="alert alert-warning" style="margin-left: auto; margin-right: auto;">Login to add, edit and delete posts !!!</div>
    }

    @if (User.Identity.IsAuthenticated)
    {
        <a asp-action="Create">
            <button type="button" class="btn bg-primary text-white" style="margin-left: auto; margin-right: auto;
                        margin-bottom: 20px; align-self:stop;">
                Add Post
            </button>
        </a>
    }
    @foreach (var item in Model)
    {
        <a style="text-decoration :none;"
           href="@Url.Action("Index", "Reply", new { id = item.Id })">
            <div class="card border-primary " style="border-width:medium; border-radius: 10px;
                                margin-left: auto; margin-right: auto;
                                margin-bottom: 10px;width: 100%">
                <div class="card-body">
                    <h3 class="card-title" style="color:black;"> @Html.DisplayFor(modelItem => item.Title)</h3>
                    <div class="d-flex justify-content-between">
                        <h6 class="card-text mb-2" style="color:black;"> @Html.DisplayFor(modelItem => item.AuthorNickname)</h6>
                        <h6 class="card-text mb-2" style="color:black;"> @Html.DisplayFor(modelItem => item.Posted)</h6>
                    </div>
                    <hr class="bg-primary" />
                    <p class="card-text" style="color:black;">   @Html.DisplayFor(modelItem => item.Description)</p>

                    @{
                        if (User.Identity.Name == item.AuthorNickname)
                        {
                            <a href="@Url.Action("Edit", "Post", new { id = item.Id })">
                                <button type="button" class="btn bg-primary text-white">Edit Post</button>
                            </a>

                            if (!User.IsInRole("moderator"))
                            {
                                <a href="@Url.Action("Delete", "Post", new { id = item.Id })">
                                    <button type="button" class="btn bg-primary text-white">Delete Post</button>
                                </a>
                            }
                        }
                        if (User.IsInRole("moderator"))
                        {
                            <a href="@Url.Action("Delete", "Post", new { id = item.Id })">
                                <button type="button" class="btn bg-primary text-white">Delete Post</button>
                            </a>
                        }
                    }
                </div>
            </div>
        </a>
        <br>
    }
</div>