WebApp/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using InternetForum.Core.Domain;
using InternetForum.WebApp.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using WebApp.Models;
using JwtRegisteredClaimNames = Microsoft.IdentityModel.JsonWebTokens.JwtRegisteredClaimNames;

namespace WebApp.Controllers
{
    public class PostController : Controller
    {
        public IConfiguration Configuration;
        private readonly UserManager<User> _userManager;

        public PostController(IConfiguration configuration, UserManager<User> userManager)
        {
            Configuration = configuration;
            _userManager = userManager;
        }

       
        public async Task<IActionResult> Index()
        {
            var tokenString = Utils.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();
            List<PostMV> posts = new List<PostMV>();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    posts = JsonConvert.DeserializeObject<List<PostMV>>(apiResponse);
                }
            }

            return View(posts);
        }
        
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var tokenString = Utils.GenerateJSONWebToken();
            string _restpath = GetHostUrl().Content + CN();
          
         
            PostMV r = new PostMV();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.DeleteAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        r = JsonConvert.DeserializeObject<PostMV>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction(nameof(Index));
            
        }
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            CreatePostMV post = new CreatePostMV();
            return await Task.Run(() => View(post));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreatePostMV post)
        {
            string _restpath = GetHostUrl().Content + CN();
            var tokenString = Utils.GenerateJSONWebToken();
            post.Author = _userManager.GetUserAsync(HttpContext.User).Result.Id;
           

            PostMV result = new PostMV();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(post);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");


                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<PostMV>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            string _restpath = GetHostUrl().Content + CN();


            PostMV post = new PostMV();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    post = JsonConvert.DeserializeObject<PostMV>(apiResponse);
                }
            }
            return View(post);
        }

        [HttpPost]
        //[Authorize]
        public async Task<IActionResult> Edit(EditPostMV post)
        {
            string _restpath = GetHostUrl().Content + CN();
            var tokenString = Utils.GenerateJSONWebToken();

            PostMV r = new PostMV();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(post);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.PutAsync($"{_restpath}/{post.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        r = JsonConvert.DeserializeObject<PostMV>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction(nameof(Index));
        }

       
       
        

        private ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            string cn = ControllerContext.RouteData.Values["controller"].ToString();
            return cn;
        }

    }
}

WebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using InternetForum.Core.Domain;
using InternetForum.WebApp.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using WebApp.Models;

namespace WebApp.Controllers
{
   
        public class UserController : Controller
        {
            public IConfiguration _configuration;
            private readonly UserManager<User> _userManager;
            public UserController(IConfiguration configuration, UserManager<User> userManager)
            {
                _configuration = configuration;
                _userManager = userManager;
            }


            public async Task<IActionResult> Index()
            {
                var tokenString = Utils.GenerateJSONWebToken();
                string _restpath = GetHostUrl().Content + CN();
                List<UserMV> usersList = new List<UserMV>();
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                    using (var response = await httpClient.GetAsync(_restpath))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        usersList = JsonConvert.DeserializeObject<List<UserMV>>(apiResponse);
                    }
                }

                return View(usersList);
            }

            [HttpGet]
            [Authorize]
            public async Task<IActionResult> Edit(int id)
            {
               string _restpath = GetHostUrl().Content + "userdetails";
           
            UserDetailsMV u = new UserDetailsMV();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                    {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    u = JsonConvert.DeserializeObject<UserDetailsMV>(apiResponse);
                    }
                }
                return View(u);
            }

            [HttpPost]
            [Authorize]
            public async Task<IActionResult> Edit(EditUserDetailsMV details)
            {
                string _restpath = GetHostUrl().Content + "userdetails";
                var tokenString = Utils.GenerateJSONWebToken();

            UserDetailsMV result = new UserDetailsMV();
                try
                {
                    using (var httpClient = new HttpClient())
                    {
                        string jsonString = System.Text.Json.JsonSerializer.Serialize(details);
                        var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);
                        using (var response = await httpClient.PutAsync($"{_restpath}/{details.Id}", content))
                        {
                        
                        string apiResponse = await response.Content.ReadAsStringAsync();
                            result = JsonConvert.DeserializeObject<UserDetailsMV>(apiResponse);
                        }
                    }
                }
                catch (Exception ex)
                {
                    return View(ex);
                }

                return RedirectToAction(nameof(Index));
            }

         

        private ContentResult GetHostUrl()
        {
            var result = _configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            string cn = ControllerContext.RouteData.Values["controller"].ToString();
            return cn;
        }

    }
}

WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using InternetForum.Core.Domain

@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3 text-white">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Post" asp-action="Index">Posts</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
            @if (SignInManager.IsSignedIn(User))
            {

                <div class="nav-item dropdown  topnav-right">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <form class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">

                            <a href="javascript:document.getElementById('logoutForm').submit()">Sign out</a>
                        </form>
                    </div>
                </div>
                <div class="nav-link text-dark topnav-right">
                    Welcome <h3>@User.Identity.Name</h3>
                </div>
            }
            else
            { 
                <div class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Sign in</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link text-danger" asp-area="" asp-controller="Account" asp-action="Register">Sign up</a>
                </div>
            }
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container" style="color:white;">
            &copy; 2022 - WebApp - <a style="color:white;" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>